version: '3'

services:
  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - loki_data:/loki
    networks:
      - loki-network

  promtail:
    image: grafana/promtail:latest
    volumes:
     - /data/compose/13/promtail-config.yaml:/etc/promtail/config.yml
     - /var/log/app
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki-network
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - loki-network
    depends_on:
      - loki

volumes:
  loki_data:
  grafana_data:

networks:
  loki-network: